version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DSN=host=db user=username password=password dbname=tasks port=5432 sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
